sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: ${OSS_ENDPOINT}
    access-key-id: ${OSS_ENDPOINT}
    access-key-secret: ${OSS_ENDPOINT}
    bucket-name: ${OSS_BUCKET_NAME}
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
    mchid: ${WECHAT_MCHID}
    mchSerialNo: ${WECHAT_MCH_SERIAL_NO}
    privateKeyFilePath: ${WECHAT_PRIVATE_KEY_PATH}
    apiV3Key: ${WECHAT_API_V3_KEY}
    weChatPayCertFilePath: ${WECHAT_CERT_PATH}
    notifyUrl: ${WECHAT_NOTIFY_URL}
    refundNotifyUrl: ${WECHAT_REFUND_NOTIFY_URL}
